#pragma once

#include <bitset>
#include <random>
#include <string>
#include <random>
#include <iostream>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <vector>
#include <queue>
#include <unordered_set>
#include <set>
#include <stack>
#include <algorithm>
#include <tuple>
#include <utility>
#include <iomanip>
#include <unordered_map>
#include <map>